### ISSUE TITLE
Multichannel

### ISSUE THREAD

**Issue by thomasgeissl** [npisanti/ofxPDSP#15]
Hello,
as already mentioned in [this](https://forum.openframeworks.cc/t/ofxpdsp-mutlichannel/30285) post i have problems working with multichannel outputs.

It seems like setting the number of inputs and outputs crashes the app.
Thanks for having a look.

**Comment by npisanti** [comment]
adding post for reference:
https://forum.openframeworks.cc/t/ofxpdsp-mutlichannel/30285

can you please state your OS and IDE ?

**Comment by thomasgeissl** [comment]
osx, 10.13.4, x-code. i was working with a focusrite scarlett 18i20.

**Comment by thomasgeissl** [comment]
i had a quick look at it myself. resizing a processors outputs vector will call the copy constructor and there pdsp_trace gets called. i am wondering why you do not allow a patch node to be copy constructed.

the move operator behaves differently, i am not sure that this is on purpose.
it returns before calling pdsp_trace().

**Comment by npisanti** [comment]
i don't want any pdsp unit to be copied around, because what happen to the other units patched to it? my choices for the API when for example a class called B has to be copied and A is connected to it would be:
1) patch all the connections from A to B and B' 
2) don't patch anything to B' 
all those choices can lead to confusion or undefined behaviors, so i preferred being clear and avoiding copy, all the inputs and outputs emits warnings that can be traced when it happens. I still don't want pdsp::PatchNode to be copied around, i'll try as a quick fix to have more inputs by default for the pdsp::Processor, and then only some could be used, i thing we could never use more than 32 channels so it could be a good max number for now.

**Comment by thomasgeissl** [comment]
thanks for explanation, makes totally sense. 
having 32 outputs and inputs by default and then reducing the number via the setChannels function should not call the copy constructor.

**Comment by npisanti** [comment]
i made the change, could you `git pull` and test it?

**Comment by thomasgeissl** [comment]
Thanks Nicola, it works perfectly. Great work!
