### ISSUE TITLE
Trouble Loading Audio File Using Relative Path

### ISSUE THREAD

**Issue by maximosigniorini** [npisanti/ofxPDSP#20]
Hi Nicola! I'm having trouble when trying to load a sound file using a relative path. I tried within the song player example player.load("sound.wav") and also player.load("bin/data/sound.wav") but neither functioned right. It gives me the following error: 
[ofxAudioFile] ERROR loading wav file
[pdsp] error loading sample
_UniCharInfo_LinearCount:888

Any help is appreciated!

All best,

Maximo.

**Comment by npisanti** [comment]
this issue should go into ofxAudioFile, but actually it's more a problem of oF, i could get relative path to works just by putting things in the data folder and using 
```cpp
player.load( ofToDataPath("sound.wav") );
```
for example. 
Relative paths are always a problem in different OS, on some platform they work, on another they don't work, `ofToDataPath()` should always work (otherwise open an issue on oF)

**Comment by npisanti** [comment]
if you are using `make run`
```
player.load( "data/sound.wav" );
```
could also work. You have to think that the relative paths starts from where your app is, so both the path you were using were plain wrong. Anyway `ofToDataPath()` its still a better idea.

**Comment by maximosigniorini** [comment]
Thanks!! ofToDataPath() worked just fine!
