### ISSUE TITLE
Reading RMS values

### ISSUE THREAD

**Issue by AnasGhrab** [npisanti/ofxPDSP#25]
Is it possible to have a small example on how to get RMS values from a signal ?

Thanks.

**Comment by npisanti** [comment]
it's already there:
https://github.com/npisanti/ofxPDSP/blob/master/example_analysis/src/AudioAnalyzerBand.cpp

**Comment by AnasGhrab** [comment]
I saw it, but I hoped something simpler ;) Anyway, thank you.

**Comment by npisanti** [comment]
if you just need RMS; probably ofxPDSP is not the best choice as RMS is calculated for each sample in the buffer, so something like 512x the cost of just doing one RMS of the whole buffer. This is because the RMS class in pdsp is used in compressors effects, that require the RMS to be done for each sample.

if you just need audio analysis, i advice you ofxGist:
https://github.com/borg/ofxGist
