### ISSUE TITLE
VAOscillator pitch frequency

### ISSUE THREAD

**Issue by AnasGhrab** [npisanti/ofxPDSP#27]
It seems that the pitch for the VAOscillator is given as MIDI values (that is not indicated in the doc..). How to set it as frequencies in Hertz ?

**Comment by npisanti** [comment]
`pdsp::VAOscillator` is an high level module made of various low level oscillators, you could copy the class and modify the code to use a "pdsp::PatchNode" instead of the `pdsp::PItchToFreq`, removing the pitch conversion this way, or if you are just setting the frequency manually via UI, you can add a listener to an ofParameter to set the controlling value by using `pdsp::f2p( float pitch )` that gives freq as result.

https://github.com/npisanti/ofxPDSP/blob/master/src/modules/oscillators/VAOscillator.h#L89
