### ISSUE TITLE
PitchToFreq class

### ISSUE THREAD

**Issue by rafadiniz** [npisanti/ofxPDSP#30]
If I want to use only frequencies, not pitches, do I have to change the source code of the VAOscillator class? In this case, editing the functions of the PitchToFreq class?

If anyone can help me I appreciate it.

rafa

**Comment by npisanti** [comment]
well, `pdsp::VAOscillator` is a module made of many different units, if you want to directly use freq maybe the best way is copy it, rename it and then modify it.

But usually it's always better to use pitch control, because it is logarithmically scaled so even in case of things that need hz control (microtonality) it's still better to convert them to pitch values using the `pdsp::f2p( float freq )` function

**Comment by rafadiniz** [comment]
Yes, that's it. I like to work thinking from the spectrum, but I haven't stopped to think that the pitch parameter receive float and there are possibilities for microtonality. This can be interesting. I will try to work like this and any other problem I will give you some feedback. Thanks!

**Comment by npisanti** [comment]
you're wellcome! 

PS: maybe you could be interested to see how managed to get a table of integer ratio tuning for various use:
https://github.com/npisanti/np-patches/blob/master/src/tuning/PureTuning.h
https://github.com/npisanti/np-patches/blob/master/src/tuning/PureTuning.cpp
