### ISSUE TITLE
Pattern abstraction?

### ISSUE THREAD

**Issue by MartinBspheroid** [npisanti/ofxPDSP#47]
Hi, first of all, thank you very much for this gem! What a piece of nice work, really... Well documented and with examples provided, it's quite easy to pick up.

That brings me to following question: apart from code I have stumbled upon in 'sequencing4 passing data' example, I could not find any other feasible way to load patterns to sequencer. 

I guess your answer will be "roll your own" but I just wonder if there's other way how to go about this or if you have any other abstraction that you could point me towards (as I might missed something, somewhere, somehow...)

Cheers

Martin

**Comment by npisanti** [comment]
yes, "roll your own" is pretty accurate as i wanted to keep the things inside ofxPDSP to the basics (and still the codebase got quite big, and still needs some trimming) 

anyway i have a separate repository with my own higher level abstractions:
https://github.com/npisanti/np-patches

the nearest thing to what you need is the probabilistic tracker, it loads a text file of space separated values for the sequence, you use it like a tracker, with some tweaks you could surely modify to make it work with horizontal sequences instead of vertical tracker-like sequences:

https://github.com/npisanti/np-patches/blob/master/src/sequence/Tracker.h
https://github.com/npisanti/np-patches/blob/master/example_tracker/src/ofApp.cpp

the text file with the sequence is also reloaded live if you modify and then save it while ofxPDSP is running

**Comment by MartinBspheroid** [comment]
Nice, that's exactly what I wanted to do. Having probability is not what I wanted at the moment as I would like to have similar behaviour to classical drum machines, so. I'll have to ditch that. 
But it's right direction and your response was pretty much instant, so I'm closing this.

Cheers

Martin

**Comment by npisanti** [comment]
well, the probability is active only if you put an x after the step value, for example:
```
1.0  <--- normal step with 1.0 value
-
0.8x0.5 <--- step with 0.8 value, 50% chance
-
```
